title: misctechmusings.com
email: asbounds@gmail.com
description: "notebook for projects, problems, and solutions"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://misctechmusings.com" # the base hostname & protocol for your site, e.g. http://example.com
author: "Andrew Bounds"

google_analytics_id: UA-15151002-2

permalink: "/:categories/:slug"

theme: minima
minima:
  skin: "primer"
# generate social links in footer
  social_links:
    github: p0rkjello
    twitter: p0rkjello
    rss: rss

utterances:
  repo: "p0rkjello/p0rkjello.github.io"
  theme: "github-light"
  issue_term: "title"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-octicons

markdown: kramdown
kramdown:
  parse_block_html: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
