title: misctechmusings.com
email: asbounds@gmail.com
description: "notebook for projects, problems, and solutions"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://misctechmusings.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: p0rkjello

google_analytics_id: UA-15151002-2

permalink: "/:categories/:slug"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  parse_block_html: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
